name: Bump version
on:
  workflow_dispatch:
    inputs:
      formula:
        description: 'formula name'
        required: true
      version:
        description: 'formula version'
        required: true
jobs:
  bump-formula-version:
    name: Bump Homebrew formula verion
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Bump
        shell: bash
        env:
          FORMULA_NAME: ${{ github.event.inputs.formula }}
          FORMULA_VERSION: ${{ github.event.inputs.version }}
        run: |
          brew tap RedMadRobot/formulae
          brew install "$FORMULA_NAME"
          cp "$FORMULA_NAME".rb $(brew formula "$FORMULA_NAME")
          brew bump-formula-pr --no-browse --no-audit --write --no-fork --version "$FORMULA_VERSION" "$FORMULA_NAME"
          brew cat "$FORMULA_NAME"
