name: Bump version
on:
  workflow_dispatch:
    inputs:
      formulae:
        description: 'formulae name'
        required: true
      version:
        description: 'formulae version'
        required: true
jobs:
  bump-formulae-version:
    name: Bump Homebrew formulae verion
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Bump
        run: |
          echo "formula: ${{ github.event.inputs.formulae }}"
          echo "verion ${{ github.event.inputs.version }}"
        shell: bash
